jms_serializer:
    visitors:
        json_deserialization:
            options: [ JSON_UNESCAPED_UNICODE ]
        json_serialization:
            options: [ JSON_UNESCAPED_UNICODE ]
        xml_serialization:
            format_output: '%kernel.debug%'

    property_naming:
        id: jms_serializer.identical_property_naming_strategy
